thing = input(' Digite Alguma Coisa : ')
print(type(thing))
print('O Que Você Digitou é Apenas Espaços :', thing.isspace())
print('O Que Você Digitou é Numerico :', thing.isnumeric())
print('O Que Você Digitou é Alfabetico :', thing.isalpha())
print('O Que Você Digitou é AlfaNumerico :', thing.isalnum())
print('O Que Voê Digitou está em Maisculo :', thing.isupper())
print('O Que Você Digitou está em Minusculo :', thing.islower())
print('O Que Você Digitou Está Capitalizado :', thing.istitle())